import React from 'react';
import { BUSINESS_ANALYST_ICON, DATA_SCIENCE_ENGINEER_ICON, DEVOPS_ENGINEER_ICON, DIGITAL_MARKETING_ICON, HUMAN_RESOURCE_ICON, LEAD_SOFTWARE_ENGINEER_ICON, PROJECT_MANAGER_ICON, SALESFORCE_ICON, SOFTWARE_ENGINEER_TESTING_ICON, SR_MOBILE_ENGINEER_ICON, SR_SOFTWARE_ENGINEER_BE_ICON, SR_SOFTWARE_ENGINEER_FE_ICON, SR_SOFTWARE_ENGINEER_ML_ICON, TECH_PROJECT_MANAGER_ICON, UI_UX_DESIGNER_ICON } from '../icons'

const iconMap = {
  "softwareEngineer": LEAD_SOFTWARE_ENGINEER_ICON,
  "frontendEngineer": SR_SOFTWARE_ENGINEER_FE_ICON,
  "backendEngineer": SR_SOFTWARE_ENGINEER_BE_ICON,
  "machineLearningEngineer": SR_SOFTWARE_ENGINEER_ML_ICON,
  "mobileEngineer": SR_MOBILE_ENGINEER_ICON,
  "devopsEngineer": DEVOPS_ENGINEER_ICON,
  "testingEngineer": SOFTWARE_ENGINEER_TESTING_ICON,
  "projectManager": TECH_PROJECT_MANAGER_ICON,
  "digitalMarketing": DIGITAL_MARKETING_ICON,
  "salesforceEngineer": SALESFORCE_ICON,
  "humanResource": HUMAN_RESOURCE_ICON,
  "dataScientist": DATA_SCIENCE_ENGINEER_ICON,
  "businessAnalyst": BUSINESS_ANALYST_ICON,
  "productManager": PROJECT_MANAGER_ICON,
  "uiuxDesigner": UI_UX_DESIGNER_ICON
} as Record<string, any>

export {iconMap};